name: Deploy Cattr Service

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository (macOS safe)
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Pull latest images
        run: docker compose -f cattr.yaml pull

      - name: Start / Update Cattr
        run: docker compose -f cattr.yaml up -d
