name: Run CATTR Service

on:
  workflow_dispatch:

jobs:
  run-cattr:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Start CATTR on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ~/.ssh/id_ed25519
          script: |
            mkdir -p ~/cattr
            cd ~/cattr
            docker compose up -d
