name: Run CATTR Service

on:
  workflow_dispatch:

jobs:
  run-cattr:
    runs-on: ubuntu-latest

    steps:
      - name: Start CATTR on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p ~/cattr
            cd ~/cattr
            docker compose up -d
