name: Run CATTR Service

on:
  workflow_dispatch:

jobs:
  run-cattr:
    runs-on: ubuntu-latest

    steps:
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Run CATTR on server
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            mkdir -p ~/cattr
            cd ~/cattr
            docker compose up -d
          EOF
