name: Deploy Gitea on Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export secrets to environment
        run: |
          echo "GITEA_EMAIL=${{ vars.GITEA_EMAIL }}" >> $GITHUB_ENV
          echo "GITEA_EMAIL_PASSWORD=${{ secrets.GITEA_EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy Gitea
        run: |
          docker swarm init || true
          docker stack deploy -c gitea-stack.yaml gitea

      - name: Verify services
        run: docker service ls
